### ISSUE TITLE
Break config into separate file

### ISSUE THREAD

**Issue by ajfisher** [nodebotsau/water-rocket#1]
At the moment the config for AP and the MQTT server are all in the code so possibility of committing something dodgy. Suggest moving to a local_settings.py file and import it and use it or similar.

**Comment by nickzoic** [comment]
My guest access point really is called "NotMyAP" :-)

If anyone really wants to drive out here for free internet I'll let 'em
have it ... but yeah, point taken, we can split it apart a bit.

**Comment by ajfisher** [comment]
Note for myself for later. Fields to break out

SSID + password
Mqtt host
Topic root

**Comment by ajfisher** [comment]
Closed by 8c4a54c30f04661b32e1470648d54b2b353ff437
